package com.example.morp_prj.notifications

/**
 * Deprecated (kept for compatibility with older branches).
 * Guest notifications are generated by real local task reminders.
 */
@Deprecated("No longer used")
object GuestNotificationsSeeder
